name: dia_body
description: Request body parser middleware for Dia http serer. Parse query, x-www-form-urlencoded, json and form-data params and uploaded files form HttpRequest.
version: 0.1.0
homepage: https://github.com/unger1984/dia_body

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.1.3
  mime: ^1.0.0
  uuid: ^3.0.4
  http_parser: ^4.0.0

dev_dependencies:
  dart_code_metrics: ^3.0.0
  pedantic: ^1.11.0
  test: ^1.16.8
  http: ^0.13.1
