name: dia_body
description: Request body parser middleware for Dia http serer.
version: 0.0.1
homepage: https://github.com/unger1984/dia_body

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.0.5
  mime: ^1.0.0
  uuid: ^3.0.3
  http_parser: ^4.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  http: ^0.13.1
