name: dia_body
description: Request body parser middleware for Dia http serer.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.0.5

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
